### ISSUE TITLE
aumenta a frequência yag

### ISSUE THREAD

**Issue by heitorfreitasferreira** [potatosenior/Twitter-Bot-Dolar#1]
isso posta pouco dms

coloca mais img tbm

**Comment by potatosenior** [comment]
Ta postando de 1h em 1h, colocar pra postar toda vez q muda o valor eu acho spam(_twitter tbm rsrs_), as img foi eu q baixei, n achei api do google pra baixar

**Comment by heitorfreitasferreira** [comment]
baixa mais foto então ai e coloca nesse diretório
